### ISSUE TITLE
Deadlines

### ISSUE THREAD

**Issue by sdudenhofer** [EugTech/OpenEugeneFestivalWeb#12]
Need to set some basic deadlines of when we need to have the site running by. With clear markers that we can aim towards.

**Comment by nohorse** [comment]
when do we need color pallet picked and header graphics?

**Comment by sdudenhofer** [comment]
The color pallet we should be able to adjust at any time through CSS, so it can be adjusted on the fly. The header graphic would be great to have sooner rather than later but again should be mostly css work to tweak.

**Comment by nohorse** [comment]
we have more design asset here: https://drive.google.com/drive/folders/1uUjRMSVGXAmakdYNjS8xnPTANnjpkXJW?usp=sharing
