### ISSUE TITLE
Content for the About Page

### ISSUE THREAD

**Issue by nohorse** [EugTech/OpenEugeneFestivalWeb#16]
The About Pages:

how about a the leadership team?  maybe pull headshots from github avatars or slack or social media

links to folks:  https://docs.google.com/spreadsheets/d/1y_-LjrMHS6El6w5sc70I2qVCtEK2gqVf2GTNMkKKTAo/edit?usp=sharing

get a blurb from mark about the history

**Comment by nohorse** [comment]
really launched at BarCamp Jan 2018 as a unconference session.

**Comment by nohorse** [comment]
Add info about the Trifoia space.  maybe Adam has a video?
Plus Claim52 kitchen back room and the other food place that catering.
Level up is right down the street as is that vegan truck everyone loves.
address with map?  google maps?

**Comment by mckelveygreg** [comment]
Do we want to post any public details of the leadership team: Github or email?

**Comment by nohorse** [comment]
GitHub or Twitter handle is ok. Email is bad. Because PII ---- On Tue, 20 Nov 2018 13:02:13 -0800  Greg McKelvey<notifications@github.com> wrote ----Do we want to post any public details of the leadership team: Github or email?  —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by mckelveygreg** [comment]
I deployed an updated about page with info and avatars about everyone on the leadership team. 
Is that the direction we were thinking?

**Comment by mckelveygreg** [comment]
Updated about with a description from the old site
