### ISSUE TITLE
Content/links for footer

### ISSUE THREAD

**Issue by mckelveygreg** [EugTech/OpenEugeneFestivalWeb#17]
What social media do we want links to?
- [x] Eugtech - twitter, facebook, github, instagram
- [x] OpenEugene facebook event

**Comment by nohorse** [comment]
let's do the "made in the shire" thing!  

https://siliconshire.org/promote/

https://siliconshire.org/static/images/stamp_made_black.png
https://siliconshire.org/static/images/stamp_made_white.png

**Comment by nohorse** [comment]
twitter: https://twitter.com/EugTech
insta: https://www.instagram.com/eugtech/
fb: https://www.facebook.com/EugTech/
github: https://github.com/EugTech

**Comment by nohorse** [comment]
event:  https://www.facebook.com/events/196679251226823/

**Comment by nohorse** [comment]
@mckelveygreg go for it!
