### ISSUE TITLE
Content for Home Page

### ISSUE THREAD

**Issue by nohorse** [EugTech/OpenEugeneFestivalWeb#20]
let's try and be fun.  transition from What's an Open Fest to Why Come to Open Fest?

- [ ] To Play KING-PONG!
- [ ] To Find my Open Source brothers and sisters in the region
- [ ] Get your hands dirty! Hack with techies, Talk with Takies?  I dunno
- [ ] Show the world your awesome project!
- [ ] Story time with Dr. Bud! SmartDown Edition
- [ ] bulk this up!

How about a video?

**Comment by mckelveygreg** [comment]
I updated the homepage with some of the new info. Perhaps it will spark ideas for more content?
I'll style it more once we get the style guide, etc...

**Comment by nohorse** [comment]
check out this doc:  https://docs.google.com/document/d/1iqbM9yJ6t_LcnskFyhiPRWMNxbFPb66ZAO3_fNto4hE/edit?usp=sharing
