### ISSUE TITLE
make a "media" page 

### ISSUE THREAD

**Issue by nohorse** [EugTech/OpenEugeneFestivalWeb#51]
We'll have some media generated before and after the event.  For example we have two blog posts and a youtube video we can link to today.  the three types of cards we should have in the list are article (blog post), video (embedded) and audio (embedded).

backstory: https://medium.com/@nohorse/mozfest-leads-to-open-eugene-festival-d8b43396023e
moz interview: https://medium.com/mozilla-festival/open-eugene-festival-open-leaders-6-8424251dde97

intro video: https://youtu.be/PZojOfxjPPg

here's a spreadsheet with some types of links: https://docs.google.com/spreadsheets/d/10UkKtvYz-MWZc9tlUrl6qJG5U_oLbx4A_jZYVrT84JU/edit?usp=sharing

**Comment by mckelveygreg** [comment]
media page made, but should we style it any differently?
