### ISSUE TITLE
complete speaker photos on session page

### ISSUE THREAD

**Issue by nohorse** [EugTech/OpenEugeneFestivalWeb#54]

**Comment by nohorse** [comment]
check out a start at feature/speaker-photos
I also added two column of data for Photo and Photo2
https://docs.google.com/spreadsheets/d/1Lur8WLuUdBYXbrFHBo3Q70gSUW17rZtpogcCBdnNP90/edit?usp=sharing

**Comment by nohorse** [comment]
there should be new entries in the json for photos
 "Photo": "nate.jpg",
    "Photo2": ""

**Comment by mckelveygreg** [comment]
Photos deployed
