### ISSUE TITLE
Create Style guide

### ISSUE THREAD

**Issue by sdudenhofer** [EugTech/OpenEugeneFestivalWeb#8]
Create a basic style guide for the website. This should be a resource that can be open sourced and used for other websites like this one. Does mozilla already have one??

**Comment by nohorse** [comment]
Magdalen is working up a style guide now.  we are adding stuff to the website issue  https://github.com/EugTech/Open-Eugene/issues/42

**Comment by mckelveygreg** [comment]
fonts and colors are integrated
